import sys
import shutil
from pathlib import Path

VERSION = "3.3.3"
RELEASE_NOTES = """
1.手柄也能识别自动钓鱼（但是启动建没有改）
2.修改跑鱼判定逻辑
"""


def generate_readme(version, notes):
    content = f"""[版本: {version}] 更新内容：
{notes}

==================================================
        PartyFish 自动钓鱼助手 - 使用说明与版本更新
==================================================
1.如果遇到游戏内按F2键没反应，游戏外有反应请右键主程序只用管理员身份运行
2.遇到其他问题需要按F10键截图并联系我
3.部分全屏时带黑边的电脑无法在全屏模式下使用此软件

--------------------------------------------------
[免责协议]
--------------------------------------------------
本软件仅供学习交流，请勿传播。
使用本软件存在被官方风控及封号的风险，由此产生的任何损失由使用者自行承担，与作者本人无关。

--------------------------------------------------
[文件结构与数据存储]
--------------------------------------------------
软件资源（不可删除）：
resources/   : 存放核心资源文件 (图片) - 已打包进 exe
resources/fish.json : 鱼类图鉴数据文件 (可自行更新数据，但请勿修改文件名) - 已打包进 exe
data/   : 存放音频和配置文件 (需手动复制到 exe 同级目录)
data/protected_fish.json : 放生保护数据文件 (可自行更新数据，但请勿修改文件名)
data/audio/ : 提示音文件夹 (需手动复制到 exe 同级目录)

用户数据与配置（重要）：
数据现已存储在 Windows 标准应用数据目录下：
%APPDATA%\Partyfish\
(可在资源管理器地址栏输入上方路径直接访问)

- config.json : 全局配置文件
- accounts/   : 多账号数据文件夹 (包含各账号的 records.csv, sales.csv)
- accounts/<账号名>/pokedex.json : 图鉴收集进度数据

自定义提示音：
如果您想更换提示音，请进入 data/audio 文件夹，替换以下文件（文件名必须保持一致）：
- no_bait.mp3        : "没鱼饵啦"提示音
- inventory_full.mp3 : "背包满啦"提示音
- start.mp3          : 启动提示音
- pause.mp3          : 暂停提示音
"""
    Path("使用说明与版本更新.txt").write_text(content, encoding="utf-8")
    print("已生成使用说明文档")


def write_version(version):
    Path("src/_version.py").write_text(
        f'# Auto-generated by build.py\n__version__ = "{version}"\n', encoding="utf-8"
    )
    print("已写入版本文件")


def run_pyinstaller():
    import subprocess

    # 清理旧的输出文件
    dist_exe = Path("dist/partyfish.exe")
    if dist_exe.exists():
        dist_exe.unlink()
        print("已清理旧输出文件")

    print("开始打包...")
    result = subprocess.run(
        [sys.executable, "-m", "PyInstaller", "partyfish_release.spec"]
    )
    if result.returncode != 0:
        print(f"打包失败，退出码: {result.returncode}")
        sys.exit(1)
    print("打包完成")


def post_build(version):
    import time

    dist_exe = Path("dist/partyfish.exe")
    target_exe = Path(f"dist/partyfish-{version}.exe")
    target_dir = Path(f"dist/partyfish-{version}")

    # 检查打包结果
    if not dist_exe.exists():
        print(f"错误: 找不到打包后的文件 {dist_exe}")
        sys.exit(1)

    # 清理旧的目标目录和文件
    if target_dir.exists():
        for i in range(5):
            try:
                shutil.rmtree(target_dir)
                break
            except PermissionError:
                if i < 4:
                    print(f"等待删除旧目录，尝试 {i+1}/5...")
                    time.sleep(2)
                else:
                    print(f"警告: 无法删除旧目录 {target_dir}")

    if target_exe.exists():
        for i in range(5):
            try:
                target_exe.unlink()
                break
            except PermissionError:
                if i < 4:
                    print(f"等待删除旧文件，尝试 {i+1}/5...")
                    time.sleep(2)
                else:
                    print(f"警告: 无法删除旧文件 {target_exe}")

    # 创建目标目录
    target_dir.mkdir(parents=True, exist_ok=True)

    # 移动 exe 到目标目录
    for i in range(5):
        try:
            shutil.move(str(dist_exe), str(target_dir / "partyfish.exe"))
            break
        except PermissionError:
            if i < 4:
                print(f"等待移动文件，尝试 {i+1}/5...")
                time.sleep(2)
            else:
                print(f"错误: 无法移动文件 {dist_exe}")
                raise

    # 复制 data 文件夹到目标目录
    if Path("data").exists():
        shutil.copytree("data", target_dir / "data", dirs_exist_ok=True)
        print("已复制 data 文件夹")

    # 复制说明文档
    readme = Path("使用说明与版本更新.txt")
    if readme.exists():
        shutil.copy2(readme, target_dir / readme.name)
        print("已复制使用说明")

    print(f"输出目录: {target_dir}")


def main():
    print("=== 开始构建 ===")
    write_version(VERSION)
    generate_readme(VERSION, RELEASE_NOTES)
    run_pyinstaller()
    post_build(VERSION)
    print("=== 构建完成 ===")


if __name__ == "__main__":
    main()
