import shutil
import subprocess
import sys
import time
from importlib.util import find_spec
from pathlib import Path

APP_NAME = "PartyFish"
SPEC_FILE = "PartyFish.spec"
VERSION = "3.3.9beta"
RELEASE_NOTES = ""
RELEASE_NOTES_FILENAME = "使用说明与版本更新.txt"

README_TEMPLATE = """[版本: {version}] 更新内容：
{notes}

==================================================
        PartyFish 自动钓鱼助手 - 使用说明与版本更新
==================================================
1.如果遇到游戏内按F2键没反应，游戏外有反应请右键主程序只用管理员身份运行
2.遇到其他问题需要按F10键截图并联系我
3.部分全屏时带黑边的电脑无法在全屏模式下使用此软件

--------------------------------------------------
[免责协议]
--------------------------------------------------
本软件仅供学习交流，请勿传播。
使用本软件存在被官方风控及封号的风险，由此产生的任何损失由使用者自行承担，与作者本人无关。

--------------------------------------------------
[文件结构与数据存储]
--------------------------------------------------
软件资源（不可删除）：
resources/   : 存放核心资源文件 (图片) - 已打包进 exe
resources/fish.json : 鱼类图鉴数据文件 (可自行更新数据，但请勿修改文件名) - 已打包进 exe
data/   : 存放音频和配置文件 (需手动复制到 exe 同级目录)
data/protected_fish.json : 放生保护数据文件 (可自行更新数据，但请勿修改文件名)
data/audio/ : 提示音文件夹 (需手动复制到 exe 同级目录)

用户数据与配置（重要）：
数据现已存储在 Windows 标准应用数据目录下：
%APPDATA%\\Partyfish\\
(可在资源管理器地址栏输入上方路径直接访问)

- config.json : 全局配置文件
- accounts/   : 多账号数据文件夹 (包含各账号的 records.csv, sales.csv)
- accounts/<账号名>/pokedex.json : 图鉴收集进度数据

自定义提示音：
如果您想更换提示音，请进入 data/audio 文件夹，替换以下文件（文件名必须保持一致）：
- no_bait.mp3        : "没鱼饵啦"提示音
- inventory_full.mp3 : "背包满啦"提示音
- start.mp3          : 启动提示音
- pause.mp3          : 暂停提示音
"""


def ensure_build_dependencies():
    missing = []

    if find_spec("PyInstaller") is None:
        missing.append("PyInstaller")

    if sys.platform == "win32" and find_spec("win32ctypes.pywin32") is None:
        missing.append("pywin32-ctypes")

    if not missing:
        return

    install_command = f"{sys.executable} -m pip install {' '.join(missing)}"
    print(f"Missing build dependencies: {', '.join(missing)}")
    print("Install them with:")
    print(f"  {install_command}")
    sys.exit(1)


def generate_release_notes(version, notes):
    content = README_TEMPLATE.format(version=version, notes=notes)
    Path(RELEASE_NOTES_FILENAME).write_text(content, encoding="utf-8")
    print(f"Generated {RELEASE_NOTES_FILENAME}")


def write_version(version):
    Path("src/_version.py").write_text(
        f'# Auto-generated by build.py\n__version__ = "{version}"\n',
        encoding="utf-8",
    )
    print("Wrote src/_version.py")


def run_pyinstaller():
    dist_exe = Path(f"dist/{APP_NAME}.exe")
    if dist_exe.exists():
        dist_exe.unlink()
        print(f"Removed existing {dist_exe}")

    print("Running PyInstaller...")
    result = subprocess.run(
        [sys.executable, "-m", "PyInstaller", SPEC_FILE], check=False
    )
    if result.returncode != 0:
        print(f"Build failed with exit code {result.returncode}")
        sys.exit(result.returncode)

    print("PyInstaller build completed")


def remove_with_retry(path, is_dir=False, attempts=5, delay_seconds=2):
    for attempt in range(1, attempts + 1):
        try:
            if is_dir:
                shutil.rmtree(path)
            else:
                path.unlink()
            return
        except FileNotFoundError:
            return
        except PermissionError:
            if attempt == attempts:
                raise
            print(f"Waiting for {path} to unlock ({attempt}/{attempts})...")
            time.sleep(delay_seconds)


def move_with_retry(source, target, attempts=5, delay_seconds=2):
    for attempt in range(1, attempts + 1):
        try:
            shutil.move(str(source), str(target))
            return
        except PermissionError:
            if attempt == attempts:
                raise
            print(f"Waiting to move {source} ({attempt}/{attempts})...")
            time.sleep(delay_seconds)


def post_build(version):
    dist_exe = Path(f"dist/{APP_NAME}.exe")
    target_dir = Path(f"dist/{APP_NAME}-{version}")

    if not dist_exe.exists():
        print(f"Build output not found: {dist_exe}")
        sys.exit(1)

    if target_dir.exists():
        remove_with_retry(target_dir, is_dir=True)

    target_dir.mkdir(parents=True, exist_ok=True)
    move_with_retry(dist_exe, target_dir / f"{APP_NAME}.exe")

    data_dir = Path("data")
    if data_dir.exists():
        shutil.copytree(data_dir, target_dir / "data", dirs_exist_ok=True)
        print("Copied data directory")

    release_notes = Path(RELEASE_NOTES_FILENAME)
    if release_notes.exists():
        shutil.copy2(release_notes, target_dir / release_notes.name)
        print(f"Copied {RELEASE_NOTES_FILENAME}")

    print(f"Build output directory: {target_dir}")


def main():
    ensure_build_dependencies()
    print("=== Starting build ===")
    write_version(VERSION)
    generate_release_notes(VERSION, RELEASE_NOTES)
    run_pyinstaller()
    post_build(VERSION)
    print("=== Build complete ===")


if __name__ == "__main__":
    main()
