import subprocess
import sys
import shutil
import os
from pathlib import Path

def get_git_version():
    """
    通过 'git describe --tags --abbrev=0' 命令获取最新的 git tag。
    """
    try:
        # 执行 git 命令
        result = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0"],
            capture_output=True,
            text=True,
            check=True,
            encoding='utf-8'
        )
        # 获取并清理版本号字符串
        version = result.stdout.strip()
        if version:
            print(f"成功获取版本号: {version}")
            return version
        else:
            print("错误: Git tag 为空。")
            return None
    except FileNotFoundError:
        print("错误: 未找到 Git 命令。请确保 Git 已安装并已在系统 PATH 中。")
        return None
    except subprocess.CalledProcessError as e:
        # 如果 git 命令返回非零退出码，则捕获异常
        print(f"错误: 'git describe' 执行失败。您是否已经创建了至少一个 tag？")
        print(f"Git 错误信息: {e.stderr.strip()}")
        return None

def get_git_tag_message(tag_name):
    """
    获取指定 tag 的注释信息作为更新日志。
    """
    try:
        # git for-each-ref refs/tags/{tag_name} --format="%(contents)"
        # 注意：Windows下需要处理引号，subprocess会自动处理list参数
        result = subprocess.run(
            ["git", "for-each-ref", f"refs/tags/{tag_name}", "--format=%(contents)"],
            capture_output=True,
            text=True,
            check=True,
            encoding='utf-8'
        )
        msg = result.stdout.strip()
        if not msg:
            return "暂无更新日志。"
        return msg
    except Exception as e:
        print(f"获取 Tag 信息失败: {e}")
        return "获取更新日志失败。"

def generate_readme(version, release_notes):
    """
    生成结合了版本更新日志和固定帮助信息的 使用说明.txt
    """
    fixed_content = f"""
==================================================
        AutoFish 自动钓鱼助手 - 使用说明与版本更新
==================================================
1.如果遇到游戏内按F2键没反应，游戏外有反应请右键主程序只用管理员身份运行
2.遇到其他问题需要按F10键截图并联系我
3.部分全屏时带黑边的电脑无法在全屏模式下使用此软件

--------------------------------------------------
[免责协议]
--------------------------------------------------
本软件仅供学习交流，请勿传播。
使用本软件存在被官方风控及封号的风险，由此产生的封号等后果由使用者自行承担，与作者本人无关。

--------------------------------------------------
[文件结构与数据存储]
--------------------------------------------------
软件资源（不可删除）：
resources/   : 存放核心资源文件 (图片、音频)
            resources/fish.json : 鱼类图鉴数据文件 (可自行更新数据，但请勿修改文件名)

用户数据与配置（重要）：
数据现已存储在 Windows 标准应用数据目录下：
%APPDATA%\\Autofish\\
(可在资源管理器地址栏输入上方路径直接访问)

- config.json : 全局配置文件
- accounts/   : 多账号数据文件夹 (包含各账号的 records.csv, sales.csv)
              - accounts/<账号名>/pokedex.json : 图鉴收集进度数据

自定义提示音：
如果您想更换提示音，请进入 resources/audio 文件夹，替换以下文件（文件名必须保持一致）：
- no_bait.mp3        : "没鱼饵啦"提示音
- inventory_full.mp3 : "背包满啦"提示音
"""
    
    full_content = f"[版本: {version}] 更新内容：\\n{{release_notes}}\\n{{fixed_content}}"
    # Corrected f-string formatting above to avoid SyntaxError with double braces for literal braces if needed, 
    # but here we want to insert variables.
    # Wait, the previous attempt had f"""...""" block. Let's make it simpler to avoid f-string complexity or escaping issues in tool calls.
    
    full_content = f"[版本: {version}] 更新内容：\\n" + release_notes + "\\n" + fixed_content
    
    readme_path = Path("使用说明与版本更新.txt")
    try:
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(full_content)
        print(f"已生成最新文档: {readme_path} (包含版本 {version} 的更新日志)")
        return True
    except Exception as e:
        print(f"生成文档失败: {e}")
        return False

def write_version_file(version):
    """
    将版本号写入 src/_version.py 文件。
    """
    version_file = Path("src") / "_version.py"
    print(f"正在写入版本号到: {version_file}")
    try:
        with open(version_file, "w", encoding='utf-8') as f:
            f.write(f'# This file is auto-generated by build.py\n')
            f.write(f'__version__ = "{version}"\n')
        print("版本文件写入成功。")
        return True
    except IOError as e:
        print(f"错误: 写入文件 {version_file} 失败: {e}")
        return False

def run_pyinstaller():
    """
    执行 PyInstaller 打包命令。
    """
    spec_file = "autofish_release.spec"
    print(f"开始执行 PyInstaller，使用 spec 文件: {spec_file}...")
    try:
        subprocess.run(
            [sys.executable, "-m", "PyInstaller", spec_file],
            check=True,
            encoding='utf-8'
        )
        print("PyInstaller 打包成功完成。")
        return True
    except FileNotFoundError:
        print(f"错误: 找不到 spec 文件 '{spec_file}'。")
        return False
    except subprocess.CalledProcessError:
        print("错误: PyInstaller 打包过程中发生错误。")
        return False

def post_build_actions(version):
    """
    打包后的后续操作：复制资源并重命名输出文件夹。
    """
    dist_path = Path("dist") / "autofish"
    target_path = Path("dist") / f"autofish-{version}"
    resources_src = Path("resources")
    resources_dst = dist_path / "resources"

    print(f"--- 开始打包后处理 (版本: {version}) ---")

    # 1. 复制 resources 目录
    if resources_src.exists():
        print(f"正在复制 resources 到 {resources_dst}...")
        try:
            if resources_dst.exists():
                shutil.rmtree(resources_dst)
            shutil.copytree(resources_src, resources_dst)
            print("resources 目录复制成功。")
        except Exception as e:
            print(f"警告: 复制 resources 目录失败: {e}")
    else:
        print("警告: 未找到 resources 目录，跳过复制。")

    # 1.5 Config directory is no longer needed in dist (generated at runtime in user_data_dir)
    # fish.json is now in resources
    print("跳过复制 config 目录 (已改为用户数据目录存储)")

    # 1.6 复制 使用说明与版本更新.txt
    readme_src = Path("使用说明与版本更新.txt")
    readme_dst = dist_path / "使用说明与版本更新.txt"
    if readme_src.exists():
        print(f"正在复制 {readme_src} 到 {readme_dst}...")
        try:
            shutil.copy2(readme_src, readme_dst)
            print("使用说明与版本更新.txt 复制成功。")
        except Exception as e:
            print(f"警告: 复制 使用说明与版本更新.txt 失败: {e}")
    else:
        print("警告: 未找到 使用说明与版本更新.txt，跳过复制。")


    # 2. 重命名输出文件夹
    if dist_path.exists():
        try:
            if target_path.exists():
                print(f"目标目录 {target_path} 已存在，正在删除旧目录...")
                shutil.rmtree(target_path)
            
            print(f"正在重命名输出目录: {dist_path} -> {target_path}")
            # 使用 os.rename 或 Path.rename，这里使用 Path.rename
            dist_path.rename(target_path)
            print(f"输出文件夹已成功重命名为: {target_path}")
            return True
        except Exception as e:
            print(f"错误: 重命名文件夹失败: {e}")
            return False
    else:
        print(f"错误: 找不到打包输出目录 {dist_path}")
        return False

def main():
    """
    主函数，协调整个构建流程。
    """
    print("--- 开始自动化构建流程 ---")
    
    # 1. 获取版本号
    version = get_git_version()
    if not version:
        print("构建失败: 无法获取版本号。")
        sys.exit(1)
        
    # 2. 写入版本文件
    if not write_version_file(version):
        print("构建失败: 无法写入版本文件。")
        sys.exit(1)
        
    # 2.5 生成动态文档
    tag_msg = get_git_tag_message(version)
    generate_readme(version, tag_msg)
        
    # 3. 运行 PyInstaller
    if not run_pyinstaller():
        print("构建失败: PyInstaller 执行失败。")
        sys.exit(1)

    # 4. 执行打包后操作 (复制资源和重命名)
    if not post_build_actions(version):
        print("构建失败: 打包后处理失败。")
        sys.exit(1)
        
    print("--- 构建流程成功结束 ---")

if __name__ == "__main__":
    main()
